### PR TITLE
Add search toolbar on editors

### PR DESCRIPTION
**Pull request by rssiy**
search toolbar allows user to find text from DocxToSource app

### CODE REVIEW

**Comment by rmboggs** [comment]
That's not a bad idea.  I think the control names are a bit generic though. Something like xXmlSource and xCodeSource, that way it is easier to keep track of while coding.

**Comment by rssiy** [comment]
xName changes was updated. Where should I log feature requests? like a file comparer between 2 files.

**Comment by rmboggs** [comment]
I like it.  Once I check it out on a Windows machine, I'll make the pull.

As far as feature requests are concerned, just open an issue and put an enhancement label on it.  A file comparison feature would be nice, I definitely see a benefit for it based on past experience.  There would be some obstacles that would need to be worked out, and they could be discussed in further detail in the issue, but I think it would be worth the time.

**Comment by rmboggs** [comment]
Works ok.  Only thing left is to make sure that you update the MainWindow.xaml.cs file to use the new names that were put in the corrisponding xaml file.  Once that is done, I'll pull it in.  Thanks

**Comment by rssiy** [comment]
its updated now. Sorry for missing this.

**Comment by rmboggs** [comment]
No problem.  Thanks for taking the time.

**Comment by rmboggs** [comment]
This is a nice addition.  It should probably be brought to the fore front more but that can be done later.  Thanks again.

**Pull request merged**
